export type TemplatePage = {
  slug: string;
  keyword: string;
  title: string;
  h1: string;
  metaDescription: string;
  category: string;
  monthlySearchVolume: number;
  difficulty: "Low" | "Medium" | "High";
  intent: "Informational" | "Commercial" | "Transactional";
  fields: string[];
  useCases: string[];
  faqs: { q: string; a: string }[];
};

export const templatePages: TemplatePage[] = [
  {
    slug: "contact-form-template",
    keyword: "contact form template",
    title: "Free Contact Form Template | FormCraft",
    h1: "Contact Form Template",
    metaDescription: "Get a free, customizable contact form template. Add it to any website in minutes — no coding required. Powered by FormCraft.",
    category: "General",
    monthlySearchVolume: 18100,
    difficulty: "High",
    intent: "Transactional",
    fields: ["Full name", "Email address", "Subject", "Message", "Phone (optional)"],
    useCases: ["Website contact page", "Agency client intake", "Support requests", "General inquiries"],
    faqs: [
      { q: "Can I add this contact form to any website?", a: "Yes. FormCraft forms embed anywhere with a single line of code — WordPress, Webflow, Squarespace, or custom HTML." },
      { q: "Will I get notified when someone fills out the form?", a: "Instantly. Set up email, Slack, or webhook notifications so you never miss a submission." },
      { q: "Is the contact form free?", a: "The free plan includes up to 3 forms and 100 responses/month. Upgrade to Pro for unlimited." },
    ],
  },
  {
    slug: "job-application-form-template",
    keyword: "job application form template",
    title: "Free Job Application Form Template | FormCraft",
    h1: "Job Application Form Template",
    metaDescription: "Collect resumes, cover letters, and applicant info with a free job application form template. Customize and publish in minutes.",
    category: "HR",
    monthlySearchVolume: 9900,
    difficulty: "Medium",
    intent: "Transactional",
    fields: ["Full name", "Email", "Phone", "Position applied for", "Resume upload", "Cover letter", "LinkedIn URL", "Availability", "Salary expectations"],
    useCases: ["Small business hiring", "Agency staffing", "Freelance contractor intake", "Internship applications"],
    faqs: [
      { q: "Can applicants upload their resume through the form?", a: "Yes. FormCraft supports file uploads up to 25MB, including PDFs, Word docs, and images." },
      { q: "Can I add screening questions?", a: "Absolutely. Use conditional logic to show follow-up questions based on role or experience level." },
      { q: "Where do submitted applications go?", a: "All submissions are stored in your FormCraft dashboard. You can also export to CSV or connect to an ATS via Zapier." },
    ],
  },
  {
    slug: "event-registration-form-template",
    keyword: "event registration form template",
    title: "Free Event Registration Form Template | FormCraft",
    h1: "Event Registration Form Template",
    metaDescription: "Let attendees register for your event online. Collect names, meal preferences, payment, and more with a free event registration form.",
    category: "Events",
    monthlySearchVolume: 8100,
    difficulty: "Medium",
    intent: "Transactional",
    fields: ["Full name", "Email", "Ticket type", "Number of guests", "Dietary requirements", "T-shirt size", "Payment"],
    useCases: ["Conferences", "Workshops", "Webinars", "Community meetups", "Corporate events"],
    faqs: [
      { q: "Can I collect payment through the registration form?", a: "Yes. FormCraft integrates with Stripe so you can charge for tickets directly in the form." },
      { q: "Can I limit the number of registrations?", a: "Yes. Set a max response limit and the form automatically closes when capacity is reached." },
      { q: "Can I send a confirmation email to attendees?", a: "Absolutely. Set up auto-reply emails with event details, calendar invites, and Zoom links." },
    ],
  },
  {
    slug: "customer-feedback-form-template",
    keyword: "customer feedback form template",
    title: "Free Customer Feedback Form Template | FormCraft",
    h1: "Customer Feedback Form Template",
    metaDescription: "Collect structured customer feedback with a free, customizable form template. NPS, ratings, and open-ended questions included.",
    category: "Survey",
    monthlySearchVolume: 6600,
    difficulty: "Medium",
    intent: "Transactional",
    fields: ["Overall satisfaction (1–5)", "NPS score", "What did we do well?", "What could we improve?", "Email (optional)", "Would you recommend us?"],
    useCases: ["Post-purchase surveys", "SaaS product feedback", "Service quality reviews", "NPS campaigns"],
    faqs: [
      { q: "Can I add an NPS question to the feedback form?", a: "Yes. FormCraft includes a built-in NPS field with automatic score tracking and segmentation." },
      { q: "Can the form show different follow-up questions based on the rating?", a: "Yes. Conditional logic lets you ask detractors (1–6) different questions than promoters (9–10)." },
      { q: "How do I analyze feedback responses?", a: "FormCraft's analytics dashboard shows response distributions, averages, and trends over time." },
    ],
  },
  {
    slug: "lead-generation-form-template",
    keyword: "lead generation form template",
    title: "Free Lead Generation Form Template | FormCraft",
    h1: "Lead Generation Form Template",
    metaDescription: "Capture more leads with a high-converting lead gen form template. Connects to HubSpot, Salesforce, and 100+ CRMs automatically.",
    category: "Marketing",
    monthlySearchVolume: 5400,
    difficulty: "Medium",
    intent: "Commercial",
    fields: ["First name", "Work email", "Company name", "Job title", "Company size", "Budget range", "How did you hear about us?"],
    useCases: ["Landing page lead capture", "Content gating", "Free trial signups", "Demo requests", "Newsletter signups"],
    faqs: [
      { q: "Can the form send leads straight to my CRM?", a: "Yes. FormCraft connects natively to HubSpot, Salesforce, and Pipedrive. For other CRMs, use Zapier." },
      { q: "How do I increase my form completion rate?", a: "Keep it short. Only ask for what you need. FormCraft's conditional logic lets you collect more data without adding visible fields." },
      { q: "Can I A/B test different versions of the form?", a: "You can create multiple form variants and compare submission rates in the analytics dashboard." },
    ],
  },
  {
    slug: "online-order-form-template",
    keyword: "online order form template",
    title: "Free Online Order Form Template | FormCraft",
    h1: "Online Order Form Template",
    metaDescription: "Accept orders online with a free order form template. Collect product selections, quantities, and payment in one simple form.",
    category: "eCommerce",
    monthlySearchVolume: 4400,
    difficulty: "Low",
    intent: "Transactional",
    fields: ["Customer name", "Email", "Shipping address", "Product/service selection", "Quantity", "Special instructions", "Payment (Stripe)"],
    useCases: ["Small business product orders", "Custom service requests", "Food pre-orders", "Print-on-demand", "Wholesale inquiries"],
    faqs: [
      { q: "Can I accept payment directly in the order form?", a: "Yes. Stripe is built into FormCraft so you can collect payment as part of the order submission." },
      { q: "Can customers select from a product list?", a: "Yes. Use dropdown, checkbox, or radio fields to let customers choose products, sizes, and variants." },
      { q: "Is there an inventory or stock limit feature?", a: "You can set a max submission limit per form or use conditional logic to show/hide out-of-stock items." },
    ],
  },
  {
    slug: "patient-intake-form-template",
    keyword: "patient intake form template",
    title: "Free Patient Intake Form Template | FormCraft",
    h1: "Patient Intake Form Template",
    metaDescription: "Collect patient information before appointments with a HIPAA-friendly intake form. Reduce paperwork and admin time.",
    category: "Healthcare",
    monthlySearchVolume: 3600,
    difficulty: "Low",
    intent: "Transactional",
    fields: ["Full name", "Date of birth", "Insurance provider", "Policy number", "Emergency contact", "Medical history", "Current medications", "Reason for visit"],
    useCases: ["Medical practices", "Dental offices", "Physical therapy", "Mental health intake", "Telehealth"],
    faqs: [
      { q: "Is FormCraft HIPAA compliant?", a: "FormCraft Pro includes Business Associate Agreement (BAA) support. Contact us to enable HIPAA-compliant data handling." },
      { q: "Can patients fill out the form before their appointment?", a: "Yes. Send a link via email or SMS and patients complete it on their phone or computer before arriving." },
      { q: "Can I use e-signatures on intake forms?", a: "Yes. FormCraft includes an e-signature field for consent forms and authorization documents." },
    ],
  },
  {
    slug: "client-onboarding-form-template",
    keyword: "client onboarding form template",
    title: "Free Client Onboarding Form Template | FormCraft",
    h1: "Client Onboarding Form Template",
    metaDescription: "Streamline new client onboarding with a professional intake form. Collect briefs, approvals, and key details before the project starts.",
    category: "Agency",
    monthlySearchVolume: 2900,
    difficulty: "Low",
    intent: "Commercial",
    fields: ["Company name", "Primary contact", "Project goals", "Target audience", "Budget", "Timeline", "Brand assets upload", "Competitors", "Success metrics"],
    useCases: ["Marketing agencies", "Freelance designers", "Web developers", "Consultants", "Coaches"],
    faqs: [
      { q: "Can clients upload brand assets through the onboarding form?", a: "Yes. File upload fields support images, PDFs, ZIP files, and more up to 25MB each." },
      { q: "Can I white-label the form with my agency branding?", a: "Yes. Pro plan includes white-label branding — remove FormCraft logos and use your own domain." },
      { q: "Can I require clients to sign off before submitting?", a: "Yes. Add an e-signature field and a checkbox for terms acknowledgment to the form." },
    ],
  },
  {
    slug: "volunteer-registration-form-template",
    keyword: "volunteer registration form template",
    title: "Free Volunteer Registration Form Template | FormCraft",
    h1: "Volunteer Registration Form Template",
    metaDescription: "Register volunteers online with a free, customizable form. Collect availability, skills, and emergency contacts in minutes.",
    category: "Nonprofit",
    monthlySearchVolume: 2400,
    difficulty: "Low",
    intent: "Transactional",
    fields: ["Full name", "Email", "Phone", "Availability (days/times)", "Skills and experience", "Areas of interest", "Emergency contact", "Background check consent"],
    useCases: ["Nonprofits", "Community organizations", "Food banks", "Animal shelters", "Event volunteering"],
    faqs: [
      { q: "Can volunteers select their availability in the form?", a: "Yes. Use a checkbox grid or date picker to let volunteers select available days and time slots." },
      { q: "Can I collect background check consent in the form?", a: "Yes. Add a consent checkbox or e-signature field for background check authorization." },
      { q: "Is there a free plan for nonprofits?", a: "Yes. The free plan includes 3 forms and 100 responses/month. Nonprofits can apply for discounted Pro access." },
    ],
  },
  {
    slug: "real-estate-inquiry-form-template",
    keyword: "real estate inquiry form template",
    title: "Free Real Estate Inquiry Form Template | FormCraft",
    h1: "Real Estate Inquiry Form Template",
    metaDescription: "Capture buyer and renter inquiries with a free real estate form template. Connect to your CRM and respond faster.",
    category: "Real Estate",
    monthlySearchVolume: 1900,
    difficulty: "Low",
    intent: "Commercial",
    fields: ["Full name", "Email", "Phone", "Property of interest", "Budget range", "Timeline to move", "Pre-approved for mortgage?", "Additional questions"],
    useCases: ["Real estate agents", "Property managers", "Rental listings", "New development sales", "Mortgage brokers"],
    faqs: [
      { q: "Can I embed the inquiry form on a property listing page?", a: "Yes. Copy the embed code and paste it anywhere — MLS sites, WordPress, or custom pages." },
      { q: "Can leads from the form go straight to my CRM?", a: "Yes. FormCraft connects to HubSpot, Salesforce, Follow Up Boss, and 100+ tools via Zapier." },
      { q: "Can I create different forms for different property types?", a: "Yes. Create unlimited forms on Pro — one per listing, neighborhood, or property type." },
    ],
  },
  {
    slug: "form-builder-for-healthcare",
    keyword: "form builder for healthcare",
    title: "Form Builder for Healthcare | FormCraft",
    h1: "Form Builder for Healthcare",
    metaDescription: "Build HIPAA-friendly patient intake, consent, and feedback forms for your healthcare practice. No coding required.",
    category: "Healthcare",
    monthlySearchVolume: 1600,
    difficulty: "Low",
    intent: "Commercial",
    fields: ["Patient intake", "Consent forms", "Appointment requests", "Insurance verification", "Post-visit feedback"],
    useCases: ["Medical practices", "Dental offices", "Mental health providers", "Telehealth platforms", "Physical therapy clinics"],
    faqs: [
      { q: "Is FormCraft suitable for healthcare providers?", a: "Yes. FormCraft Pro includes BAA support for HIPAA-compliant data handling and encrypted storage." },
      { q: "Can patients e-sign consent forms?", a: "Yes. The e-signature field is available on Pro and works on mobile devices." },
      { q: "Can I collect insurance information through the form?", a: "Yes. Add custom fields for insurance provider, policy number, and group ID." },
    ],
  },
  {
    slug: "form-builder-for-real-estate",
    keyword: "form builder for real estate",
    title: "Form Builder for Real Estate Agents | FormCraft",
    h1: "Form Builder for Real Estate",
    metaDescription: "Create buyer inquiry, seller intake, and open house sign-in forms for your real estate business. Embed on any site, connect to any CRM.",
    category: "Real Estate",
    monthlySearchVolume: 1300,
    difficulty: "Low",
    intent: "Commercial",
    fields: ["Buyer inquiry", "Seller intake", "Open house sign-in", "Mortgage pre-qualification", "CMA request"],
    useCases: ["Independent agents", "Real estate teams", "Brokerages", "Property managers", "Mortgage brokers"],
    faqs: [
      { q: "Can I create different forms for buyers vs. sellers?", a: "Yes. Create unlimited forms on Pro with different fields, branding, and notification rules." },
      { q: "Can open house sign-in forms work on a tablet?", a: "Yes. FormCraft forms are mobile-optimized and work on iPad kiosk mode." },
      { q: "Do leads sync to my real estate CRM?", a: "Yes. Connect to Follow Up Boss, BoomTown, Salesforce, and 100+ other tools via native integrations or Zapier." },
    ],
  },
];

export function getTemplatePage(slug: string): TemplatePage | undefined {
  return templatePages.find((p) => p.slug === slug);
}
